### ISSUE TITLE
Enhancement: Prompt users when no file extensions are found in a directory.

### ISSUE THREAD

**Issue by AustinCGomez** [AustinCGomez/Python-File-Mover-CLI#37]
We need to come up with a way that prompts the user when no files are found in a certain directory when we utilize the MoveFilesCommand class. 

**Example A:  'We did not file any file extensions within Directory_A'**
-  Send the error message prompt above.
- Re-route the user to let them pick a different folder.

**Comment by burd5** [comment]
Tried to submit a pull request for this but was denied access. Guess I need to be added as a contributor first?

**Comment by locaaustin** [comment]
Hi @burd5  -Are you trying to pull requests directly to this repo and not your own fork? If that is the case then you would have to fork the Python-File-Mover-CLI on your own github first. You would then need to do: 

- Write your code for the enhancement on your own github fork of this project. (burd5/Python-File-Mover-CLI) 
- Go to the Pull Request tab on your own fork of this repo and request to make a pull request between repos.
-  Mention this issue #37 on your Pull Request Text. 

I will then review and test your enhancement and likely approve it for addition to the main fork here.  Thank you for taking up working on this enhancement. :)

**Comment by burd5** [comment]
Hey @AustinCGomez, I figured out what I did wrong. Just resent the request. Thanks for the help!

**Comment by locaaustin** [comment]
Not a problem. Thanks!
