### ISSUE TITLE
Enhancement: Adding a python class on sending files to recycle bin. 

### ISSUE THREAD

**Issue by AustinCGomez** [AustinCGomez/Python-File-Mover-CLI#39]
There is already a PyPi function available called 'Send2Trash' `pip install send2trash` so we do not need to reinvent the wheel in regards to thinking of a way to send files to the Recylce Bin.  We just need to implement the features of send2trash into our own command for sending files to the recylce bin. **You can, however, submit a solution without using send2trash.**

Requirements: 

- The new class should be named MoveFilesToTrashCommand.
- The new command itself should be an option within our already existing interactive menu.

**Comment by tomerkt** [comment]
hello, I misunderstood what you want the send to trash feature to do: do you want the user to choose a folder and move it entirely to trash? or rather having to choose specific file types from the folder that will be trashed?

**Comment by locaaustin** [comment]
Hi @tomerkt Sorry on any confusion. It was to send files to the recycle bin from any directory based on extension. 

Someone has already submitted a pull request #41  for this enhancement in regards to moving to trash by file extension , and I will wait for them to submit a solution. 

**However, I also like the idea of moving entire folders to the recycle bin and if you want to open up an issue for that enhanement we can discussit further. Thanks**.

**Comment by AustinCGomez** [comment]
#41

**Comment by locaaustin** [comment]
Merged #41 from @Sorena1994 to fix this issue.
