### ISSUE TITLE
Log the actions of the program to a document folder.

### ISSUE THREAD

**Issue by AustinCGomez** [AustinCGomez/Python-File-Mover-CLI#54]
Request: 
Every action should be logged into a text file each time that the program functions are ran. This is so the user has a log of every action taken in the event they want to come back and remember what they did with the program. 

Suggested Approach: 
You could use standard read and write methods by Python. However you can be as creative as you want. We should log all of the files into a location on the computer such as in the documents section which is generally a safe spot. 

Our log files should be output to something such as 'PythonFileMover-Logs.txt' and each entry could look like the below: 
                                                               XX-XX-XXXX - Command Used - Details

Example: 

11-12-2024 -'--move_folders' - moved folder in documents/art to thumbdrive/two.

**Feel free to suggest or submit a pull request for your own method or think of an out of the box idea. It's open source software and all ideas are valid and appreciated!**

**Comment by locaaustin** [comment]
Cancelled
