### ISSUE TITLE
Case sensitive file types

### ISSUE THREAD

**Issue by AustinCGomez** [AustinCGomez/Python-File-Mover-CLI#57]
Program does not seem to move all .jpeg files if they are JPEG, for example,.

**Comment by malikrohail** [comment]
can i fix this?

**Comment by locaaustin** [comment]
@malikrohail Absolutely, let me know if any help is needed.

**Comment by malikrohail** [comment]
<img width="920" alt="Screenshot 2024-11-10 at 6 46 48 PM" src="https://github.com/user-attachments/assets/51c6932d-4a5a-403e-b460-3c27394fb6d5">
please look at the above screenshot and let me know. I created a test folder, and the exisiting code seems to be capturing all formats of JPEG

**Comment by malikrohail** [comment]
<img width="1026" alt="Screenshot 2024-11-10 at 7 03 37 PM" src="https://github.com/user-attachments/assets/4035952b-934e-4e38-a18e-4402c0743aeb">
fixed please accept my PR

**Comment by locaaustin** [comment]
@malikrohail fixed issue with PR #60  - Closing
