### ISSUE TITLE
Inabilty to select multiple folders with --move-folders command.

### ISSUE THREAD

**Issue by AustinCGomez** [AustinCGomez/Python-File-Mover-CLI#59]
Issue:
-mfolders only allows the user to pick one folder at a time. We should be able to pick up as many folders as a user wants and then move all of those folders at the time.

Implementation suggestion: 
We could have a command prompt in the terminal that asks a simply -y or -n if the user wants to add more files. If they pick -y then we will add more files and if they pick -n then we will only move the folders that are currently selected.  We would then use a for loop to move all of the folders using the existing shutil command. 

_Implementation suggestion is merely a suggestion. You are welcome to propose a different solution entirely and we will consider approving it or not. _

**Comment by malikrohail** [comment]
can i fix this

**Comment by locaaustin** [comment]
@malikrohail Absolutely, let me know if any help is needed.

**Comment by AustinCGomez** [comment]
@malikrohail Absolutely, let me know if any help is needed.

**Comment by malikrohail** [comment]
I’ve noticed that tkinter’s filedialog.askdirectory() doesn’t natively support selecting multiple folders in a single dialog. Would you suggest any alternatives or professional approaches for this?

**Comment by malikrohail** [comment]
I was considering options like looping to select multiple folders or using a CLI-based solution if necessary. if you have experience with any other libraries that handle this more intuitively?

**Comment by locaaustin** [comment]
That's true with the filedialog.askdirectory() it does not seem to natively support multiple folders. I had taken a bit of time to do some research and there is a altnerative to filedialog that is customer and might work. https://github.com/j4321/tkFileBrowser 

Easiest solution might be to do the looping but main concern might be if it is confusing to the user or not.

**Comment by locaaustin** [comment]
After some thinking I think I would do the loop method. Continue to add folders and display each folder into the CLI until the user decides to stop by clicking cancel or typing something and then loop through the existing function to move each folder behind the scenes. 

It may not be the best designed approach though but just an idea here. Whatever is the most fun if you still want to work on it and i'll take a look at it then. Cheers.

**Comment by locaaustin** [comment]
@malikrohail sunsetting Python File Mover and will be cancelling this issue. Have a good one.
