### ISSUE TITLE
Infinite Loop: Pressing the cancel button in the GUI menus.

### ISSUE THREAD

**Issue by AustinCGomez** [AustinCGomez/Python-File-Mover-CLI#61]
How to replicate: Use the --move-files or --move-folders command and wait for it to open the GUI menus. When we press the cancel button it'll go into a infinite loop until you cancel out of the command line interface altogether.

Possible solution: We could create a counter that records each time it opens up again and after 3 times we can suspend the program bringing it out of the loop and inform with a error message. Another option is simply to have our code do something when cancelled is pressed.

**Comment by locaaustin** [comment]
Cancelled
