### ISSUE TITLE
Make the S & M menu output more aesthically pleasing.

### ISSUE THREAD

**Issue by AustinCGomez** [AustinCGomez/Python-File-Mover-CLI#9]
Currently, it is not very pretty with what the file search prints out. I think there is a way we can make it prettier outputs.

**Comment by locaaustin** [comment]
Example

.txt files moved: 

- text1.txt
- text2.txt

.png files moved:

- png1.png
- png2.png 

.jpg files moved:

- jpg1.jpg
- jpg2.jpg

**Comment by AustinCGomez** [comment]
Assigning this to myself.
